name: Deploy Bicep with OIDC

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Azure CLI with OIDC
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Bicep file
              run: |
                az deployment sub create --location australiaeast --template-file \Infrastructure\main.bicep --parameters environment=dev location=australiaeast